# Arquivo de segredos para o Streamlit
# Contém chaves de API e outras informações sensíveis

# Chave da API do Google Gemini
# Adicione a chave apenas nas configurações de segredos do Streamlit Cloud
# GEMINI_API_KEY = "sua-chave-aqui"
